

default:
	(cd Lib ; make ) 
	(cd Programs ; make ) 
	(cd Test ; make ) 

checkin:
	(cd Lib ; make checkin )
	(cd Programs ; make checkin )
	(cd Test ; make checkin )

checkin2:
	(cd Lib ; make checkin2 )
	(cd Programs ; make checkin2 )
	(cd Test ; make checkin2 )

clean:
	(cd Lib ; make clean )
	(cd Programs ; make clean )
	(cd Test ; make clean )

realclean:
	(cd Lib ; make realclean )
	(cd Programs ; make realclean )
	(cd Test ; make realclean )
